### PR TITLE
prevent modifying the actual oriigin object when extending it

### PR DESCRIPTION
**Pull request by arnellebalane**
`extend` returns another object which is the `origin` object extened by the `add`, but the original/actual `origin` object also gets modified. This pull request is a fix to that pass-by-reference issue.

### CODE REVIEW

**Comment by kindkaktus** [comment]
@arnellebalane  I share your pain. I think the author doesn't want this patch because it bloats the code twice ;)

**Comment by rmg** [comment]
While I agree with you that it's a little annoying that it modifies the origin, that is actually the intended behaviour and therefor a "feature" required for it to be the same as `util._extend` from node core. There should actually be a test to assert that behaviour..

Another "feature" of this implementation is that it only accepts 2 arguments, so you can't even use the workaround of `extend({}, a, b);`.

At the end of the day, this module is probably not what people actually want to use. Better would be using [`Object.assign`](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Object/assign) from ES6 (or a polyfill) or _.extend() from lodash/underscore.

**Comment by isaacs** [comment]
Yeah, working as intended.

**Comment by arnellebalane** [comment]
Oh I understand, thanks a lot! :)

**Pull request closed without merging**
